### ISSUE TITLE
US-13 WorkPanelTest.java

### ISSUE THREAD

**Issue by ajbowen1** [ser316asu/Grunewald_SER316#16]
This test fails when run.

**Comment by mzomorodi** [comment]
Reconfigured the Ant script to include the JUnit jar in the classpath, as well as any files in src/.../meoranda/ui/.

**Comment by mzomorodi** [comment]
Please confirm that this issue is resolved so Task #38 can be moved to Ready for Test.

**Comment by bhood2** [comment]
This test still fails when run.

**Comment by mzomorodi** [comment]
Have you added the junit.jar to the lib directory? Also, can you verify that WorkPanelTest.java exists in the src directory?

**Comment by bhood2** [comment]
Test passes.
